# Generated by Django 3.0.3 on 2020-05-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoCategories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='author',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
