# Generated by Django 3.0.3 on 2020-05-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoCategories', '0002_video_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='image',
            field=models.ImageField(upload_to='Catgimages'),
        ),
    ]
