# Generated by Django 3.0.3 on 2020-05-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoCategories', '0003_auto_20200523_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(upload_to='thumbnails'),
        ),
    ]
